FORMAT: 1A
HOST: https://goharvey.com

# Harvey API
Notes for internal API consumption via Vue.js: [Laravel Documentation](https://laravel.com/docs/5.4/passport#consuming-your-api-with-javascript).

We make every attempt to adhere to [json-api standards](http://jsonapi.org/format/).

Suggestions or corrections may be directed to engineers@goharvey.com.
<hr>
Last Update: 2017-09-04
<hr><br>

<!-- include(groups/auth.apib) -->
<!-- include(groups/user.apib) -->
<!-- include(groups/patient.apib) -->
<!-- include(groups/attachment.apib) -->
<!-- include(groups/prescription.apib) -->
<!-- include(groups/soap_note.apib) -->
<!-- include(groups/intake.apib) -->
<!-- include(groups/search.apib) -->
<!-- include(groups/practitioner.apib) -->
<!-- include(groups/appointment.apib) -->
<!-- include(groups/lab_test.apib) -->
<!-- include(groups/lab_tests_information.apib) -->
<!-- include(groups/lab_tests_results.apib) -->
<!-- include(groups/lab_order.apib) -->
<!-- include(groups/message.apib) -->
<!-- include(groups/discount_code.apib) -->
<!-- include(groups/pagination.apib) -->
<!-- include(groups/error.apib) -->
