# Group LabTest Information
## List LabTest Information [/api/v1/lab/tests/information]
### Get LabTest information [GET]

Get a list of the current Lab Tests we offer.

+ No auth required.

+ Parameters
    + per_page: `2` (number, optional) - Enables pagination and set items per page.
+ Request
    + Headers
        X-Requested-With: XMLHttpRequest
        Content-Type: application/json
+ Response 200 (application/json)
    + Headers
    + Body
        <!-- include(../responses/api/v1/lab/tests/get-information.json) -->
