# Group LabTest
## List LabTests [/api/v1/lab/tests{?per_page,include}]
### List LabTests [GET]

View a listing of lab-tests.

+ No special role required.

+ Parameters
    + per_page: `2` (number, optional) - Enables pagination and set items per page.
    + include: `lab_order` (string, optional) - Join relationship data.
        + Members
            + `patient`
            + `practitioner`
            + `lab_order`
            + `sku`
            + `results`
+ Request
    + Headers
        Authorization: Bearer {{ ACCESS_TOKEN }}
        X-Requested-With: XMLHttpRequest
        Content-Type: application/json
+ Response 200 (application/json)
    + Headers
    + Body
        <!-- include(../responses/api/v1/lab/get-tests.json) -->

## Create LabTest [/api/v1/lab/tests]
### Create a LabTest [POST]

Create a new lab-test. Since any lab test belongs to one lab order, you need to submit the lab_order_id to put this new lab-test under. Requires Admin.

+ Request Example

    + Attributes
        + lab_order_id: `15` (number, required) - LabOrder, must be a valid ID.
        + sku_id: `12` (number, required) - SKU, must be a valid ID.
        + status: `shipped` (enum[string], optional) - LabTest status.
            + Members
                + `canceled`
                + `complete`
                + `confirmed`
                + `mailed`
                + `processing`
                + `received`
                + `recommended`
                + `shipped`
            + default: 'recommended'
        + shipment_code: `0342404938294` (string, optional) - Any string, no validation.

    + Headers
        Authorization: Bearer {{ ACCESS_TOKEN }}
        X-Requested-With: XMLHttpRequest
        Content-Type: application/json
    + Body
        {
            "lab_order_id": 15,
            "sku_id": 12,
        }

+ Response 201 (application/json)
    + Headers
    + Body
        <!-- include(../responses/api/v1/lab/post-tests.json) -->

## Get LabTest [/api/v1/lab/tests/{lab_test_id}{?per_page,include}]
### Get a LabTest [GET]

Get a LabTest by its ID.

+ Require Admin or current logged in User as the Patient or Practitioner of the LabOrder associated with this LabTest.

+ Parameters
    + include: `results` (string, optional) - Join relationship data.
        + Members
            + `patient`
            + `practitioner`
            + `lab_order`
            + `sku`
            + `results`
    + lab_test_id: `1` (number, required) - Must be a valid ID.


+ Request
    + Headers
        Authorization: Bearer {{ ACCESS_TOKEN }}
        X-Requested-With: XMLHttpRequest
        Content-Type: application/json
+ Response 200 (application/json)
    + Headers
    + Body
        <!-- include(../responses/api/v1/lab/tests/get-1.json) -->

## Update a LabTest [/api/v1/lab/tests/{lab_test_id}]
### Update LabTest [PATCH]

+ Require Admin or current logged in User as Practitioner of the LabOrder associated with this LabTest.

+ Parameters

    + lab_test_id: `1` (number, required) - Must be a valid ID.

+ Request Example

    + Attributes

        + status: `shipped` (enum[string], optional) - LabTest status.
            + Members
                + `canceled`
                + `complete`
                + `confirmed`
                + `mailed`
                + `processing`
                + `received`
                + `recommended`
                + `shipped`

    + Headers
        Authorization: Bearer {{ ACCESS_TOKEN }}
        X-Requested-With: XMLHttpRequest
        Content-Type: application/json
    + Body
        {
            "status": "mailed",
        }
+ Response 200 (application/json)
    + Headers
    + Body
        <!-- include(../responses/api/v1/lab/tests/patch-3.json) -->

## Delete LabTest [/api/v1/lab/tests/{lab_test_id}]
### Delete a LabTest [DELETE]

+ Admin role required.

+ Parameters
    + lab_test_id: `1` (number, required) - Must be a valid ID.

+ Request
    + Headers
        Authorization: Bearer {{ ACCESS_TOKEN }}
        X-Requested-With: XMLHttpRequest
        Content-Type: application/json
+ Response 204 (application/json)
