# Group Message
## List Messages [/api/v1/messages]
### List Messages [GET]

View a listing of messages associated to the authorized user (Admin role can get any message by using 'recipient_user_id' parameter).

+ Parameters
    + filter: `unread` (string, optional) - Set a filter for messages
        + Members
            + `unread`
    + recipient_user_id: `3` (number, optional) - Get messages for an specific recipient, only Admin can set this parameter. This value will be automatically set to the current logged in user_id.
    + sender_user_id: `3` (number, optional) - Get messages by an specific sender.
    + term: `medicine` (string, optional) - Filter results looking for string inside message body.
    + per_page: `3` (number, optional) - Enables pagination and set items per page.
    + include: `recipient` (string, optional) - Join relationship data (User).
        + Members
            + `sender`
            + `recipient`
+ Request
    + Headers
        Authorization: Bearer {{ ACCESS_TOKEN }}
        X-Requested-With: XMLHttpRequest
        Content-Type: application/json
+ Response 200 (application/json)
    + Headers
    + Body
        <!-- include(../responses/api/v1/get-messages.json) -->

## Get Message [/api/v1/messages/1]
### Get a Message [GET]
View details of a specific message.

+ Require Admin or current logged in User as the Sender or Recipient of the message.

+ Parameters
    + include: `recipient` (string, optional) - Join relationship data (User).
        + Members
            + `sender`
            + `recipient`
+ Request
    + Headers
        Authorization: Bearer {{ ACCESS_TOKEN }}
        X-Requested-With: XMLHttpRequest
        Content-Type: application/json
+ Response 200 (application/json)
    + Headers
    + Body
        <!-- include(../responses/api/v1/messages/get-1.json) -->

## Mark a message as read [/api/v1/messages/1/read]
### Mark a message as read [PUT]

+ Require Admin or current logged in User as Recipient of the message.

+ Request
    + Headers
        Authorization: Bearer {{ ACCESS_TOKEN }}
        X-Requested-With: XMLHttpRequest
        Content-Type: application/json
+ Response 200 (application/json)
    + Headers
    + Body
        <!-- include(../responses/api/v1/messages/get-2.json) -->

## Create Message [/api/v1/messages]
### Create a Message [POST]

+ No special role required.

+ Parameters
    + recipient_user_id: `9` (number, required) - Recipient, must be a valid ID.
    + message: `Hi there!` (string, optional) - Message body.
    + subject: `Hello` (string, optional) - Message subject.
+ Request
    + Headers
        Authorization: Bearer {{ ACCESS_TOKEN }}
        X-Requested-With: XMLHttpRequest
        Content-Type: application/json
    + Body
        {
            "recipient_user_id": 9,
            "message": "Hi there!",
            "subject": "This is the subject..."
        }
+ Response 201 (application/json)
    + Headers
    + Body
        <!-- include(../responses/api/v1/post-messages.json) -->

## Delete a Message [/api/v1/messages/5]
### Delete a Message [DELETE]

+ Admin role required.

+ Request
    + Headers
        Authorization: Bearer {{ ACCESS_TOKEN }}
        X-Requested-With: XMLHttpRequest
        Content-Type: application/json
+ Response 204 (application/json)
