# Group Patient
## List Patients [/api/v1/patients{?include,per_page}]
### List Patients [GET]

View a listing of enabled patients.

+ Admin or Practitioner role required.

+ Parameters
    + per_page: `10` (number, optional) - Enables pagination and set items per page.
    + include: `appointments` (string, optional) - Join relationship data.
        + Members
            + `user`
            + `appointments`
            + `intake`

+ Request Example

    + Headers

            Authorization: Bearer {{ ACCESS_TOKEN }}
            X-Requested-With: XMLHttpRequest
            Content-Type: application/json

+ Response 200 (application/json)

    + Headers

    + Body

            <!-- include(../responses/api/v1/patients/get.json) -->

## Get Patient [/api/v1/patients/{patient_id}{?include}]
### Get Patient [GET]

+ Require Admin, Practitioner or logged in Patient matching requested patient_id.

+ Parameters
    + patient_id: `1` (number, required) - Must be a valid ID.
    + include: `intake` (string, optional) - Join relationship data.
        + Members
            + `user`
            + `appointments`
            + `intake`

+ Request Example

    + Headers

            Authorization: Bearer {{ ACCESS_TOKEN }}
            X-Requested-With: XMLHttpRequest
            Content-Type: application/json

+ Response 200 (application/json)

    + Headers

    + Body

            <!-- include(../responses/api/v1/patients/1/get?include=intake.json) -->

## Update Patient [/api/v1/patients/{patient_id}]
### Update Patient [PATCH]

Update a patient&#39;s information.

+ Require Admin, Practitioner or logged in Patient matching requested patient_id.

+ Parameters
    + patient_id: `1` (number, required) - Must be a valid ID.

+ Request Example
    + Attributes
        + birthdate: `1982-11-01` (string, optional) - "Y-m-d" format.
        + height_inches: `3` (number, optional) - Must be integer.
        + height_feet: `5` (number, optional) - Must be integer.
        + weight: `120` (number, optional) - Must be integer.

    + Headers

            Authorization: Bearer {{ ACCESS_TOKEN }}
            X-Requested-With: XMLHttpRequest
            Content-Type: application/json

    + Body

            {
                "birthdate": "1984-12-19",
                "height_feet": 6,
                "height_inches": 1,
                "weight": 210
            }

+ Response 200 (application/json)

    + Headers

    + Body

            <!-- include(../responses/api/v1/patients/1/patch.json) -->

## List Patient Attachments [/api/v1/patients/{patient_id}/attachments{?per_page}]
### List Patient Attachments [GET]

View a listing of enabled patients.

+ Require Admin, Practitioner or logged in Patient matching requested patient_id.

+ Parameters
    + per_page: `5` (number, optional) - Enables pagination and set items per page.

+ Request Example

    + Headers

            Authorization: Bearer {{ ACCESS_TOKEN }}
            X-Requested-With: XMLHttpRequest
            Content-Type: application/json

+ Response 200 (application/json)

    + Headers

    + Body

            <!-- include(../responses/api/v1/patients/get.json) -->

## Get Patient Attachment [/api/v1/patients/{patient_id}/attachments/{attachment_id}]
### Get Patient Attachment [GET]

Gets an Attachment associated to a Patient.

+ Require Admin, Practitioner or logged in Patient matching requested patient_id. Attachment must belong to Patient.

+ Parameters
    + patient_id: `1` (number, required) - Must be a valid ID.
    + attachment_id: `2` (number, required) - Must be a valid ID.

+ Request Example

    + Headers

            Authorization: Bearer {{ ACCESS_TOKEN }}
            X-Requested-With: XMLHttpRequest
            Content-Type: application/json

+ Response 200 (application/json)

    + Headers

    + Body

            <!-- include(../responses/api/v1/patients/1/attachments/2/get.json) -->

## Create Patient Attachment [/api/v1/patients/{patient_id}/attachments]
### Create Patient Attachment [POST]

Creates an Attachment associated to a Patient.
This endpoint response includes an 'url' key, its value is a temporary link to the uploaded file (valid for 12hs).

+ Require Admin, Practitioner or logged in Patient matching patient_id. Attachment will belong to Patient.

+ Parameters
    + patient_id: `1` (number, required) - Must be a valid ID.

+ Request Example

    + Attributes

        + file: uploadedFile.pdf (string, required) - Attachment file. Allowed formats are bmp, img, jpeg, pdf and png.
        + name: My Attachment (string, optional) - A name for the Attachment, 64 characters max.
        + notes: Some quick note... (string, optional) - Quick notes associated to the Attachment, 1024 characters max.

    + Headers

            Authorization: Bearer {{ ACCESS_TOKEN }}
            X-Requested-With: XMLHttpRequest
            Content-Type: application/json

+ Response 200 (application/json)

    + Headers

    + Body

            <!-- include(../responses/api/v1/patients/1/attachments/post.json) -->

## Delete Patient Attachment [/api/v1/patients/{patient_id}/attachments/{attachment_id}]
### Delete Patient Attachment [DELETE]

Deletes an Attachment associated to a Patient.

+ Require Admin, Practitioner or logged in Patient matching requested patient_id. Attachment must belong to Patient.

+ Parameters
    + patient_id: `2` (number, required) - Must be a valid ID.
    + attachment_id: `19` (number, required) - Must be a valid ID.

+ Request Example

    + Headers

            Authorization: Bearer {{ ACCESS_TOKEN }}
            X-Requested-With: XMLHttpRequest
            Content-Type: application/json

+ Response 204 (application/json)

    + Headers

    + Body
