# Group Patient
## List Patients [/api/v1/patients{?include,per_page}]
### List Patients [GET]

View a listing of enabled patients.

+ Admin or Practitioner role required.

+ Parameters
    + per_page: `10` (number, optional) - Enables pagination and set items per page.
    + include: `appointments` (string, optional) - Join relationship data.
        + Members
            + `user`
            + `appointments`
            + `intake`
            + `soap_notes`
            + `attachments`
            + `prescriptions`
            + `lab_orders`

+ Request Example

    + Headers

            Authorization: Bearer {{ ACCESS_TOKEN }}
            X-Requested-With: XMLHttpRequest
            Content-Type: application/json

+ Response 200 (application/json)

    + Headers

    + Body

            <!-- include(../responses/api/v1/patients/get.json) -->

## Get Patient [/api/v1/patients/{patient_id}{?include}]
### Get Patient [GET]

+ Require Admin, Practitioner or logged in Patient matching requested patient_id.

+ Parameters
    + patient_id: `31` (number, required) - Must be a valid ID.
    + include: `attachments,intake,prescriptions,soap_notes,lab_orders.lab_tests.results` (string, optional) - Join relationship data, dot concatenation supported.
        + Members
            + `user`
            + `appointments`
            + `intake`
            + `soap_notes`
            + `attachments`
            + `prescriptions`
            + `lab_orders`

+ Request Example

    + Headers

            Authorization: Bearer {{ ACCESS_TOKEN }}
            X-Requested-With: XMLHttpRequest
            Content-Type: application/json

+ Response 200 (application/json)

    + Headers

    + Body

            <!-- include(../responses/api/v1/patients/31/get?include=attachments,intake,prescriptions,soap_notes,lab_orders.lab_tests.results.json) -->

## Update Patient [/api/v1/patients/{patient_id}]
### Update Patient [PATCH]

Update a patient&#39;s information.

+ Require Admin, Practitioner or logged in Patient matching requested patient_id.

+ Parameters
    + patient_id: `1` (number, required) - Must be a valid ID.

+ Request Example
    + Attributes
        + birthdate: `1982-11-01` (string, optional) - "Y-m-d" format.
        + height_inches: `3` (number, optional) - Must be integer.
        + height_feet: `5` (number, optional) - Must be integer.
        + weight: `120` (number, optional) - Must be integer.

    + Headers

            Authorization: Bearer {{ ACCESS_TOKEN }}
            X-Requested-With: XMLHttpRequest
            Content-Type: application/json

    + Body

            {
                "birthdate": "1984-12-19",
                "height_feet": 6,
                "height_inches": 1,
                "weight": 210
            }

+ Response 200 (application/json)

    + Headers

    + Body

            <!-- include(../responses/api/v1/patients/1/patch.json) -->
