# Group Patient Prescription
## List Prescriptions [/api/v1/prescriptions{?per_page}]
### List Prescriptions [GET]

Gets all the Prescriptions for the current logged in user.
Admin, Practitioner role: Gets all the prescriptions.
Patient role: Gets prescriptions assigned or created by current Patient.

+ Parameters
    + per_page: `3` (number, optional) - Enables pagination and set items per page.

+ Request Example

    + Headers

            Authorization: Bearer {{ ACCESS_TOKEN }}
            X-Requested-With: XMLHttpRequest
            Content-Type: application/json

+ Response 200 (application/json)

    + Headers

    + Body

            <!-- include(../responses/api/v1/patients/1/prescriptions/get.json) -->

## Get Prescription [/api/v1/prescriptions/{prescription_id}]
### Get Prescription [GET]

Gets a Prescription associated to a Patient.

+ Require Admin, Practitioner or logged in Patient matching requested patient_id. Prescription must belong to Patient.

+ Parameters
    + patient_id: `1` (number, required) - Must be a valid ID.
    + prescription_id: `2` (number, required) - Must be a valid ID.

+ Request Example

    + Headers

            Authorization: Bearer {{ ACCESS_TOKEN }}
            X-Requested-With: XMLHttpRequest
            Content-Type: application/json

+ Response 200 (application/json)

    + Headers

    + Body

            <!-- include(../responses/api/v1/patients/1/prescriptions/2/get.json) -->

## Create Prescription [/api/v1/patients/{patient_id}/prescriptions]
### Create Prescription [POST]

Creates a Prescription associated to a Patient.
This endpoint response includes an 'url' key, its value is a temporary link to the uploaded file (valid for 12hs).

+ Require Admin or Practitioner. Prescription will belong to Patient.

+ Parameters
    + patient_id: `1` (number, required) - Must be a valid ID.

+ Request Example

    + Attributes

        + file: uploadedFile.pdf (string, required) - Prescription file. Allowed formats are bmp, img, jpeg, pdf and png.
        + notes: Some quick note... (string, optional) - Quick notes associated to the Prescription, 1024 characters max.

    + Headers

            Authorization: Bearer {{ ACCESS_TOKEN }}
            X-Requested-With: XMLHttpRequest
            Content-Type: application/json

+ Response 200 (application/json)

    + Headers

    + Body

            <!-- include(../responses/api/v1/patients/1/prescriptions/post.json) -->

## Delete Prescription [/api/v1/prescriptions/{prescription_id}]
### Delete Prescription [DELETE]

Deletes a Prescription associated to a Patient.

+ Require Admin, Practitioner.

+ Parameters
    + patient_id: `3` (number, required) - Must be a valid ID.
    + prescription_id: `12` (number, required) - Must be a valid ID.

+ Request Example

    + Headers

            Authorization: Bearer {{ ACCESS_TOKEN }}
            X-Requested-With: XMLHttpRequest
            Content-Type: application/json

+ Response 204 (application/json)

    + Headers

    + Body
