# Group Patient SOAP Note
## List Patient SOAP Notes [/api/v1/soap_notes{?per_page}]
### List Patient SOAP Notes [GET]

Gets all the Prescriptions for the current logged in user.
Admin, Practitioner role: Gets all the prescriptions.
Patient role: Gets prescriptions assigned or created by current Patient. For this role, 'subjective', 'objective' and 'assessment' values are hidden.

+ Parameters
    + per_page: `3` (number, optional) - Enables pagination and set items per page.

+ Request Example as Practitioner

    + Headers

            Authorization: Bearer {{ ACCESS_TOKEN }}
            X-Requested-With: XMLHttpRequest
            Content-Type: application/json

+ Response 200 (application/json)

    + Headers

    + Body

            <!-- include(../responses/api/v1/patients/1/soap_notes/get.json) -->

## Get Patient SOAP Note [/api/v1/soap_notes/{soap_note_id}]
### Get Patient SOAP Note [GET]

Gets an SOAP Note associated to a Patient.

+ Require Admin, Practitioner or logged in Patient matching requested patient_id. SOAP Note must belong to Patient.
+ If request is made by Patient, 'subjective', 'objective' and assessment' values are hidden.

+ Parameters
    + patient_id: `1` (number, required) - Must be a valid ID.
    + soap_note_id: `3` (number, required) - Must be a valid ID.

+ Request Example as Patients

    + Headers

            Authorization: Bearer {{ ACCESS_TOKEN }}
            X-Requested-With: XMLHttpRequest
            Content-Type: application/json

+ Response 200 (application/json)

    + Headers

    + Body

            <!-- include(../responses/api/v1/patients/1/soap_notes/3/get.json) -->

## Create Patient SOAP Note [/api/v1/patients/{patient_id}/soap_notes]
### Create Patient SOAP Note [POST]

Creates an SOAP Note associated to a Patient.

+ Require Admin or Practitioner. SOAP Note will belong to Patient.

+ Parameters
    + patient_id: `1` (number, required) - Must be a valid ID.

+ Request Example

    + Attributes

        + subjective: Some (string, optional) - Subjective value, 2048 characters max.
        + objective: Random (string, optional) - Objective value, 2048 characters max.
        + assessment: Test (string, optional) - Assessment value, 2048 characters max.
        + plan: String (string, optional) - Plan value, 2048 characters max.

    + Headers

            Authorization: Bearer {{ ACCESS_TOKEN }}
            X-Requested-With: XMLHttpRequest
            Content-Type: application/json

+ Response 200 (application/json)

    + Headers

    + Body

            <!-- include(../responses/api/v1/patients/1/soap_notes/post.json) -->

## Delete Patient SOAP Note [/api/v1/soap_notes/{soap_note_id}]
### Delete Patient SOAP Note [DELETE]

Deletes an SOAP Note associated to a Patient.

+ Require Admin, Practitioner.

+ Parameters
    + patient_id: `3` (number, required) - Must be a valid ID.
    + soap_note_id: `12` (number, required) - Must be a valid ID.

+ Request Example

    + Headers

            Authorization: Bearer {{ ACCESS_TOKEN }}
            X-Requested-With: XMLHttpRequest
            Content-Type: application/json

+ Response 204 (application/json)

    + Headers

    + Body
